# Generated by Django 5.1.3 on 2024-11-25 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nutrition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack'), ('other', 'Other')], max_length=100)),
                ('food_items', models.TextField(help_text='List of food items consumed')),
                ('calories', models.PositiveIntegerField(help_text='Total calories consumed')),
                ('protein', models.FloatField(help_text='Protein intake in grams')),
                ('carbs', models.FloatField(help_text='Carbohydrate intake in grams')),
                ('fats', models.FloatField(help_text='Fat intake in grams')),
                ('date', models.DateField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
